{"@timestamp":"2020-10-24T06:15:19.6910440+03:00","level":"Error","messageTemplate":"{State:l}","message":"Execution BackgroundServerProcess is still in the Failed state for 00:01:18.4015801 due to an exception, will be retried no more than in 00:00:15","exceptions":[{"Depth":0,"ClassName":"System.Data.SqlClient.SqlException","Message":"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)","Source":"Core .Net SqlClient Data Provider","StackTraceString":"   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()\n   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)\n   at Hangfire.SqlServer.SqlServerStorage.UseConnection(DbConnection dedicatedConnection, Action`1 action)\n   at Hangfire.SqlServer.SqlServerConnection.AnnounceServer(String serverId, ServerContext context)\n   at Hangfire.Server.BackgroundServerProcess.CreateServer(BackgroundServerContext context)\n   at Hangfire.Server.BackgroundServerProcess.Execute(Guid executionId, BackgroundExecution execution, CancellationToken stoppingToken, CancellationToken stoppedToken, CancellationToken shutdownToken)\n   at Hangfire.Server.BackgroundProcessingServer.RunServer(Guid executionId, Object state)\n   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146232060,"HelpURL":null},{"Depth":1,"ClassName":"System.AggregateException","Message":"One or more errors occurred. (nodename nor servname provided, or not known)","Source":"System.Private.CoreLib","StackTraceString":"   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233088,"HelpURL":null},{"Depth":2,"ClassName":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException","Message":"nodename nor servname provided, or not known","Source":"System.Net.NameResolution","StackTraceString":"   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.ResolveCallback(Object context)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)\n   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Data.SqlClient.SNI.SNITCPHandle.ConnectAsync(String serverName, Int32 port)","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":5,"HelpURL":null}],"fields":{"State":"Execution BackgroundServerProcess is still in the Failed state for 00:01:18.4015801 due to an exception, will be retried no more than in 00:00:15","SourceContext":"Hangfire.Processing.BackgroundExecution","Application":"NIC.SBCPlatform.SharedModules.Api"},"renderings":{"State":[{"Format":"l","Rendering":"Execution BackgroundServerProcess is still in the Failed state for 00:01:18.4015801 due to an exception, will be retried no more than in 00:00:15"}]}}
{"@timestamp":"2020-10-24T06:15:19.7723960+03:00","level":"Debug","messageTemplate":"{State:l}","message":"Execution loop BackgroundServerProcess:b40c5ff4 caught an exception and will be retried in 00:00:15","exceptions":[{"Depth":0,"ClassName":"System.Data.SqlClient.SqlException","Message":"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)","Source":"Core .Net SqlClient Data Provider","StackTraceString":"   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()\n   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)\n   at Hangfire.SqlServer.SqlServerStorage.UseConnection(DbConnection dedicatedConnection, Action`1 action)\n   at Hangfire.SqlServer.SqlServerConnection.AnnounceServer(String serverId, ServerContext context)\n   at Hangfire.Server.BackgroundServerProcess.CreateServer(BackgroundServerContext context)\n   at Hangfire.Server.BackgroundServerProcess.Execute(Guid executionId, BackgroundExecution execution, CancellationToken stoppingToken, CancellationToken stoppedToken, CancellationToken shutdownToken)\n   at Hangfire.Server.BackgroundProcessingServer.RunServer(Guid executionId, Object state)\n   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146232060,"HelpURL":null},{"Depth":1,"ClassName":"System.AggregateException","Message":"One or more errors occurred. (nodename nor servname provided, or not known)","Source":"System.Private.CoreLib","StackTraceString":"   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233088,"HelpURL":null},{"Depth":2,"ClassName":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException","Message":"nodename nor servname provided, or not known","Source":"System.Net.NameResolution","StackTraceString":"   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.ResolveCallback(Object context)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)\n   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Data.SqlClient.SNI.SNITCPHandle.ConnectAsync(String serverName, Int32 port)","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":5,"HelpURL":null}],"fields":{"State":"Execution loop BackgroundServerProcess:b40c5ff4 caught an exception and will be retried in 00:00:15","SourceContext":"Hangfire.Processing.BackgroundExecution","Application":"NIC.SBCPlatform.SharedModules.Api"},"renderings":{"State":[{"Format":"l","Rendering":"Execution loop BackgroundServerProcess:b40c5ff4 caught an exception and will be retried in 00:00:15"}]}}
{"@timestamp":"2020-10-24T06:15:19.7727820+03:00","level":"Debug","messageTemplate":"{State:l}","message":"Execution loop BackgroundServerProcess:b40c5ff4 will be retried in 00:00:15...","fields":{"State":"Execution loop BackgroundServerProcess:b40c5ff4 will be retried in 00:00:15...","SourceContext":"Hangfire.Processing.BackgroundExecution","Application":"NIC.SBCPlatform.SharedModules.Api"},"renderings":{"State":[{"Format":"l","Rendering":"Execution loop BackgroundServerProcess:b40c5ff4 will be retried in 00:00:15..."}]}}
